name: LightningTPA
main: com.lightningtpa.LightningTPA
api-version: "1.20"
version: 1.0.0
author: LightningTPA
description: Premium TPA plugin with PvP cooldown system and home teleportation

permissions:
  lightningtpa.tpa:
    description: Allows player to send TPA requests
    default: true
    children:
      lightningtpa.tpahere: true
  
  lightningtpa.tpahere:
    description: Allows player to send TPAHere requests
    default: true
  
  lightningtpa.accept:
    description: Allows player to accept TPA requests
    default: true
  
  lightningtpa.deny:
    description: Allows player to deny TPA requests
    default: true
  
  lightningtpa.home:
    description: Allows player to use home commands
    default: true
    children:
      lightningtpa.home.set: true
      lightningtpa.home.delete: true
  
  lightningtpa.home.set:
    description: Allows player to set homes
    default: true
  
  lightningtpa.home.delete:
    description: Allows player to delete homes
    default: true

commands:
  tpa:
    description: Send a teleport request to a player
    usage: /tpa <player>
    permission: lightningtpa.tpa
    permission-message: "&cYou don't have permission to use this command!"
    permission-complete: false
    aliases: [tpask]
    tabcomplete:
      - $PLAYERS
  
  tpahere:
    description: Send a teleport here request to a player
    usage: /tpahere <player>
    permission: lightningtpa.tpahere
    permission-message: "&cYou don't have permission to use this command!"
    permission-complete: false
    tabcomplete:
      - $PLAYERS
  
  tpaccept:
    description: Accept a pending teleport request
    usage: /tpaccept
    permission: lightningtpa.accept
    permission-message: "&cYou don't have permission to use this command!"
    permission-complete: false
  
  tpdeny:
    description: Deny a pending teleport request
    usage: /tpdeny
    permission: lightningtpa.deny
    permission-message: "&cYou don't have permission to use this command!"
    permission-complete: false
  
  home:
    description: Manage and teleport to homes
    usage: |
      /home set <name> - Set a home
      /home <name> - Teleport to a home
      /home delete <name> - Delete a home
    permission: lightningtpa.home
    permission-message: "&cYou don't have permission to use this command!"
    permission-complete: false
    tabcomplete:
      - set
      - delete
      - '$PLAYER_HOMES'